# create country references
country <- c("Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", 
              "Australia", "Austria", "Azerbaijan", "Bahamas (The)", "Bahrain", "Bangladesh", "Barbados", "Belarus", 
              "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", 
              "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cambodia", "Cameroon", "Canada", "Cape Verde", 
              "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros", "Congo (Democratic Republic of the)", 
              "Congo (Republic of the)", "Cook Islands", "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czech Republic", 
              "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea",
              "Eritrea", "Estonia", "Eswatini", "Ethiopia", "Fiji", "Finland", "France", "Gabon", "Gambia (The)", 
              "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", 
              "Haiti", "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", 
              "Italy", "Ivory Coast", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Korea (North)", 
              "Korea (South)", "Kosovo", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", 
              "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Macedonia (North)", "Madagascar", "Malawi", 
              "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico", 
              "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar", 
              "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "Niue", 
              "Norway", "Oman", "Pakistan", "Palau", "Palestine", "Panama", "Papua New Guinea", "Paraguay", "Peru", 
              "Philippines", "Poland", "Portugal", "Qatar", "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis", 
              "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", 
              "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", 
              "Solomon Islands", "Somalia", "South Africa", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", 
              "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo",
              "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", 
              "United Arab Emirates", "United Kingdom", "United States", "Uruguay", "Uzbekistan", "Vanuatu", "Vatican City",
              "Venezuela", "Vietnam", "Western Sahara", "Yemen", "Zambia", "Zimbabwe")

region <- c("South Central Asia", "Southern Europe", "North Africa", "Southern Europe", "Central Africa", "Caribbean", 
             "South America", "Western Asia", "Australia/Oceania", "Western Europe", "Western Asia", "Caribbean", 
             "Middle East", "South Central Asia", "Caribbean", "Eastern Europe", "Western Europe", "Central America", 
             "West Africa", "South Central Asia", "South America", "Southern Europe", "Southern Africa", "South America", 
             "Southeast Asia", "Eastern Europe", "West Africa", "Eastern Africa", "Southeast Asia", "Central Africa", 
             "North America", "West Africa", "Central Africa", "Central Africa", "South America", "Eastern Asia", 
             "South America", "Eastern Africa", "Central Africa", "Central Africa", "Oceania/Polynesia", "Central America", 
             "Southern Europe", "Caribbean", "Western Asia", "Eastern Europe", "Northern Europe", "Eastern Africa", 
             "Caribbean", "Caribbean", "South America", "North Africa", "Central America", "Central Africa", 
             "Eastern Africa", "Northern Europe", "Southern Africa", "Eastern Africa", "Oceania/Melanesia", "Northern Europe", 
             "Western Europe", "Central Africa", "West Africa", "Western Asia", "Western Europe", "West Africa", 
             "Southern Europe", "Caribbean", "Central America", "West Africa", "West Africa", "South America", "Caribbean", 
             "Central America", "Eastern Europe", "Northern Europe", "South Central Asia", "Southeast Asia", 
             "South Central Asia", "Middle East", "Northern Europe", "Middle East", "Southern Europe", "West Africa", 
             "Caribbean", "Eastern Asia", "Middle East", "South Central Asia", "Eastern Africa", "Oceania/Micronesia", 
             "Eastern Asia", "Eastern Asia" ,"Southern Europe", "Middle East", "South Central Asia", "Southeast Asia", 
             "Northern Europe", "Middle East", "Southern Africa", "West Africa", "North Africa", "Western Europe", 
             "Northern Europe", "Western Europe", "Southern Europe", "Eastern Africa", "Eastern Africa", "Southeast Asia", 
             "South Central Asia", "West Africa", "Southern Europe", "Oceania/Micronesia", "West Africa", "Eastern Africa", 
             "North America", "Oceania/Micronesia", "Eastern Europe", "Southern Europe", "Eastern Asia", "Southern Europe", 
             "North Africa", "Eastern Africa", "Southeast Asia", "Southern Africa", "Oceania/Micronesia", "South Central Asia", 
             "Western Europe", "Australia/Oceania", "Central America", "West Africa", "West Africa", "Oceania/Polynesia", 
             "Northern Europe", "Middle East", "South Central Asia", "Oceania/Micronesia", "Middle East", "Central America", 
             "Oceania/Melanesia", "South America", "South America", "Southeast Asia", "Eastern Europe", "Southern Europe", 
             "Middle East", "Eastern Europe", "Eastern Europe", "Eastern Africa", "Caribbean", "Caribbean", "Caribbean", 
             "Oceania/Polynesia", "Southern Europe", "West Africa", "Middle East", "West Africa", "Southern Europe", 
             "Eastern Africa", "West Africa", "Southeast Asia", "Eastern Europe", "Southern Europe", "Oceania/Melanesia", 
             "Eastern Africa", "Southern Africa", "North Africa", "Southern Europe", "South Central Asia", "North Africa", 
             "South America", "Northern Europe", "Western Europe", "Middle East", "Eastern Asia", "South Central Asia", 
             "Eastern Africa", "Southeast Asia", "Southeast Asia", "West Africa", "Oceania/Polynesia", "Caribbean", 
             "North Africa", "Western Asia", "South Central Asia", "Oceania/Polynesia", "Eastern Africa", "Eastern Europe", 
             "Middle East", "Northern Europe", "North America", "South America", "South Central Asia", "Oceania/Melanesia", 
             "Southern Europe", "South America", "Southeast Asia", "West Africa", "Middle East", "Eastern Africa", 
             "Eastern Africa")

continent <- c("Asia", "Europe", "Africa", "Europe", "Africa", "North America", "South America", "Asia", "Oceania", 
                "Europe", "Asia", "North America", "Asia", "Asia", "North America", "Europe", "Europe", 
                "North America","Africa", "Asia", "South America", "Europe", "Africa", "South America", "Asia", 
                "Europe", "Africa", "Africa", "Asia", "Africa", "North America", "Africa", "Africa", "Africa", 
                "South America", "Asia", "South America", "Africa", "Africa", "Africa", "Oceania", "North America", 
                "Europe", "North America", "Asia", "Europe", "Europe", "Africa", "North America", "North America", 
                "South America", "Africa", "North America", "Africa", "Africa", "Europe", "Africa", "Africa", 
                "Oceania", "Europe", "Europe", "Africa", "Africa", "Asia", "Europe", "Africa", "Europe", 
                "North America", "North America", "Africa", "Africa", "South America", "North America", 
                "North America", "Europe", "Europe", "Asia", "Asia", "Asia", "Asia", "Europe", "Asia", "Europe", 
                "Africa", "North America", "Asia", "Asia", "Asia", "Africa", "Oceania", "Asia", "Asia", "Europe", 
                "Asia", "Asia", "Asia", "Europe", "Asia", "Africa", "Africa", "Africa", "Europe", "Europe", 
                "Europe", "Europe", "Africa", "Africa", "Asia", "Asia", "Africa", "Europe", "Oceania", "Africa", 
                "Africa", "North America", "Oceania", "Europe", "Europe", "Asia", "Europe", "Africa", "Africa", 
                "Asia", "Africa", "Oceania", "Asia", "Europe", "Oceania", "North America", "Africa", "Africa", 
                "Oceania", "Europe", "Asia", "Asia", "Oceania", "Asia", "North America", "Oceania", "South America", 
                "South America", "Asia", "Europe", "Europe", "Asia", "Europe", "Europe", "Africa", "North America", 
                "North America", "North America", "Oceania",  "Europe", "Africa", "Asia", "Africa", "Europe", 
                "Africa", "Africa", "Asia", "Europe", "Europe", "Oceania", "Africa", "Africa", "Africa", "Europe", 
                "Asia", "Africa", "South America", "Europe", "Europe", "Asia", "Asia", "Asia", "Africa", "Asia", 
                "Asia", "Africa", "Oceania", "North America", "Africa", "Europe", "Asia", "Oceania", "Africa", 
                "Europe", "Asia", "Europe", "North America", "South America", "Asia", "Oceania", "Europe", 
                "South America", "Asia", "Africa", "Asia", "Africa", "Africa")
geo_tags <- tibble(country, region, continent)

