# create country references
country <- c("Russia", "Canada", "United States", "China", "Brazil", "Australia", "India", "Argentina", "Kazakhstan", "Algeria", "Congo, Democratic Republic of the", "Greenland", "Saudi Arabia", "Mexico", "Indonesia", "Sudan", "Libya", "Iran", "Mongolia", "Peru", "Chad", "Niger", "Angola", "Mali", "Tibet", "South Africa", "Colombia", "Ethiopia", "Bolivia", "Mauritania", "Egypt", "Tanzania", "Nigeria", "Venezuela", "Namibia", "Mozambique", "Pakistan", "Turkey", "Chile", "Zambia", "Myanmar", 
             "Afghanistan", "Somalia", "Central African Republic", "Ukraine", "Madagascar", "Botswana", "Kenya", "France", "Yemen", "Thailand", "Spain", "Turkmenistan", "Cameroon", "Papua New Guinea", "Sweden", "Uzbekistan", "Morocco", "Iraq", "Paraguay", "Zimbabwe", "Japan", "Germany", "Congo, Republic of the", "Finland", "Vietnam", "Malaysia", "Norway", "Cote d'Ivoire", "Poland", "Oman", "Italy", "Philippines", "Ecuador", "Burkina Faso", "New Zealand", "Gabon", "Western Sahara", "Guinea", 
             "United Kingdom", "Uganda", "Ghana", "Romania", "Laos", "Guyana", "Belarus", "Kyrgyzstan", "Senegal", "Syria", "Cambodia", "Uruguay", "Suriname", "Tunisia", "Nepal", "Bangladesh", "Tajikistan", "Greece", "Nicaragua", "Korea, North", "Malawi", "Eritrea", "Benin", "Honduras", "Liberia", "Bulgaria", "Cuba", "Guatemala", "Iceland", "Korea, South", "Hungary", "Portugal", "Jordan", "Azerbaijan", "French Guiana", "Austria", "United Arab Emirates", "Czech Republic", "Serbia", "Panama", 
             "Sierra Leone", "Ireland", "Georgia", "Sri Lanka", "Lithuania", "Latvia", "Svalbard", "Togo", "Croatia", "Bosnia and Herzegovina", "Costa Rica", "Slovakia", "Dominican Republic", "Estonia", "Denmark", "Netherlands", "Switzerland", "Bhutan", "Taiwan", "Guinea-Bissau", "Moldova", "Belgium", "Lesotho", "Armenia", "Solomon Islands", "Albania", "Equatorial Guinea", "Burundi", "Haiti", "Rwanda", "Macedonia", "Djibouti", "Belize", "Israel", "El Salvador", "Slovenia", "New Caledonia", 
             "Fiji", "Kuwait", "Swaziland", "Timor-Leste", "Bahamas, The", "Montenegro", "Vanuatu", "Falkland Islands (Islas Malvinas)", "Qatar", "Gambia, The", "Jamaica", "Kosovo", "Lebanon", "Cyprus", "Puerto Rico", "Palestinian territories", "Brunei", "Trinidad and Tobago", "French Polynesia", "Cape Verde", "Samoa", "Luxembourg", "Réunion", "Comoros", "Mauritius", "Guadeloupe", "Faroe Islands", "Hong Kong", "Martinique", "Netherlands Antilles", "São Tomé and Príncipe", "Sao Tome and Principe", 
             "Turks and Caicos Islands", "Dominica", "Tonga", "Bahrain", "Kiribati", "Singapore", "Micronesia, Federated States of", "Isle of Man", "Guam", "Saint Lucia", "Palau", "Northern Mariana Islands", "Andorra", "Seychelles", "Antigua and Barbuda", "Barbados", "Saint Vincent and the Grenadines", "Virgin Islands", "Grenada", "Malta", "Maldives", "Cayman Islands", "Saint Kitts and Nevis", "Niue", "Saint Pierre and Miquelon", "Cook Islands", "American Samoa", "Marshall Islands", "Aruba", 
             "Liechtenstein", "British Virgin Islands", "Wallis and Futuna", "Saint Helena", "Jersey", "Montserrat", "Anguilla", "Guernsey", "San Marino", "Bermuda", "Norfolk Island", "Tuvalu", "Nauru", "Tokelau", "Gibraltar", "Pitcairn Islands", "Monaco", "Holy See (Vatican City)")
region <- c("Europe", "North America", "North America", "Eastern Asia", "South America", "Australia/Oceania", "South Central Asia", "South America", "South Central Asia", "North Africa", "Central Africa", "Northern Europe;", "Middle East", "North America", "Southeast Asia", "North Africa", "North Africa", "South Central Asia", "Eastern Asia", "South America", "Central Africa", "West Africa", "Central Africa", "West Africa", "Asia", "Southern Africa", "South America", "Eastern Africa", 
            "South America", "West Africa", "North Africa", "Eastern Africa", "West Africa", "South America", "Southern Africa", "Eastern Africa", "South Central Asia", "Western Asia, Southern Europe", "South America", "Eastern Africa", "Southeast Asia", "South Central Asia", "Eastern Africa", "Central Africa", "Eastern Europe", "Eastern Africa", "Southern Africa", "Eastern Africa", "Western Europe", "Middle East", "Southeast Asia", "Southern Europe", "South Central Asia", "Central Africa", 
            "Oceania, Melanesia", "Northern Europe", "South Central Asia", "North Africa", "Middle East", "South America", "Eastern Africa", "Eastern Asia", "Western Europe", "Central Africa", "Northern Europe", "Southeast Asia", "Southeast Asia", "Northern Europe", "West Africa", "Eastern Europe", "Middle East", "Southern Europe", "Southeast Asia", "South America", "West Africa", "Oceania; Australia", "Central Africa", "North Africa", "West Africa", "Northern Europe", "Eastern Africa", 
            "West Africa", "Eastern Europe", "Southeast Asia", "South America, Northern", "Eastern Europe", "South Central Asia", "West Africa", "Middle East", "Southeast Asia", "South America", "South America", "North Africa", "South Central Asia", "South Central Asia", "South Central Asia", "Southern Europe", "Central America", "Eastern Asia", "Eastern Africa", "Eastern Africa", "West Africa", "Central America", "West Africa", "Eastern Europe", "Caribbean", "Central America", 
            "Northern Europe", "Eastern Asia", "Eastern Europe", "Southern Europe", "Middle East", "Western Asia", "South America", "Western Europe", "Middle East", "Eastern Europe", "Southern Europe", "Central America", "West Africa", "Northern Europe", "Western Asia", "South Central Asia", "Northern Europe", "Northern Europe", "Northern Europe", "West Africa", "Southern Europe", "Southern Europe", "Central America", "Eastern Europe", "Caribbean", "Northern Europe", "Northern Europe", 
            "Western Europe", "Western Europe", "South Central Asia", "Eastern Asia", "West Africa", "Eastern Europe", "Western Europe", "Southern Africa", "Western Asia", "Oceania, Melanesia", "Southern Europe", "Central Africa", "Eastern Africa", "Caribbean", "Eastern Africa", "Southern Europe", "Eastern Africa", "Central America", "Middle East", "Central America", "Southern Europe", "Oceania, Melanesia", "Oceania, Melanesia", "Middle East", "Southern Africa", "Southeast Asia", "Caribbean", 
            "Southern Europe", "Oceania, Melanesia", "South America", "Middle East", "West Africa", "Caribbean", "Southern Europe", "Middle East", "Western Asia", "Caribbean", "Middle East", "Southeast Asia", "Caribbean", "Oceania, Polynesia", "West Africa", "Oceania, Polynesia", "Western Europe", "Eastern Africa", "Eastern Africa", "Eastern Africa", "Caribbean", "Northern Europe", "Eastern Asia", "Caribbean", "Caribbean", "Central Africa", "", "Caribbean", "Caribbean", "Oceania, Polynesia", 
            "Middle East", "Oceania, Micronesia", "Southeast Asia", "Oceania, Micronesia", "Northern Europe", "Oceania, Micronesia", "Caribbean", "Oceania, Micronesia", "Oceania, Micronesia", "Southern Europe", "Eastern Africa", "Caribbean", "Caribbean", "Caribbean", "Caribbean", "Caribbean", "Southern Europe", "South Central Asia", "Caribbean", "Caribbean", "Oceania, Polynesia", "North America", "Oceania, Polynesia", "Oceania, Polynesia", "Oceania, Micronesia", "Caribbean", "Western Europe", 
            "Caribbean", "Oceania, Polynesia", "West Africa", "Northern Europe", "Caribbean", "Caribbean", "Northern Europe", "Southern Europe", "Caribbean", "Oceania, Australia", "Oceania, Polynesia", "Oceania, Micronesia", "Oceania/Australia", "Southern Europe", "Oceania, Polynesia", "Southern Europe", "Southern Europe")
continent <- c("Europe", "North America", "North America", "Asia", "South America", "Oceania", "Asia", "South America", "Asia", "Africa", "Africa", "Europe", "Asia", "North America", "Asia", "Africa", "Africa", "Asia", "Asia", "South America", "Africa", "Africa", "Africa", "Africa", "Asia", "Africa", "South America", "Africa", "South America", "Africa", "Africa", "Africa", "Africa", "South America", "Africa", "Africa", "Asia", "Europe", "South America", "Africa", "Asia", "Asia", "Africa", 
               "Africa", "Europe", "Africa", "Africa", "Africa", "Europe", "Asia", "Asia", "Europe", "Asia", "Africa", "Oceania", "Europe", "Asia", "Africa", "Asia", "South America", "Africa", "Asia", "Europe", "Africa", "Europe", "Asia", "Asia", "Europe", "Africa", "Europe", "Asia", "Europe", "Asia", "South America", "Africa", "Oceania", "Africa", "Africa", "Africa", "Europe", "Africa", "Africa", "Europe", "Asia", "South America", "Europe", "Asia", "Africa", "Asia", "Asia", "South America", 
               "South America", "Africa", "Asia", "Asia", "Asia", "Europe", "North America", "Asia", "Africa", "Africa", "Africa", "North America", "Africa", "Europe", "North America", "North America", "Europe", "Asia", "Europe", "Europe", "Asia", "Asia", "South America", "Europe", "Asia", "Europe", "Europe", "North America", "Africa", "Europe", "Asia", "Asia", "Europe", "Europe", "Europe", "Africa", "Europe", "Europe", "North America", "Europe", "North America", "Europe", "Europe", "Europe", 
               "Europe", "Asia", "Asia", "Africa", "Europe", "Europe", "Africa", "Asia", "Oceania", "Europe", "Africa", "Africa", "North America", "Africa", "Europe", "Africa", "North America", "Asia", "North America", "Europe", "Oceania", "Oceania", "Asia", "Africa", "Asia", "North America", "Europe", "Oceania", "South America", "Asia", "Africa", "North America", "Europe", "Asia", "Asia", "North America", "Asia", "Asia", "North America", "Oceania", "Africa", "Oceania", "Europe", "Africa", 
               "Africa", "Africa", "North America", "Europe", "Asia", "North America", "North America", "Africa", "North America", "North America", "North America", "Oceania", "Asia", "Oceania", "Asia", "Oceania", "Europe", "Oceania", "North America", "Oceania", "Oceania", "Europe", "Africa", "North America", "North America", "North America", "North America", "North America", "Europe", "Asia", "North America", "North America", "Oceania", "North America", "Oceania", "Oceania", "Oceania", 
               "North America", "Europe", "North America", "Oceania", "Africa", "Europe", "North America", "North America", "Europe", "Europe", "North America", "Oceania", "Oceania", "Oceania", "Oceania", "Europe", "Oceania", "Europe", "Europe")

geo_tags <- tibble(country, region, continent)