target_tb <- tribble(
  ~index,                                      ~goal,                                                                                    ~target,
  "1.1",                               "No Poverty",                                                                "Eradicate extreme poverty",
  "1.2",                               "No Poverty",                                                                           "Reduce by half",
  "1.3",                               "No Poverty",                                                                "Social protection systems",
  "1.4",                               "No Poverty",                                                                             "Equal rights",
  "1.5",                               "No Poverty",                                                            "Resilience to economic shocks",
  "1.a",                               "No Poverty",                                                                "Mobilization of resources",
  "1.b",                               "No Poverty",                                                                        "Policy frameworks",
  "2.1",                              "Zero Hunger",                                                                   "Ensure sufficient food",
  "2.2",                              "Zero Hunger",                                                                         "End malnutrition",
  "2.3",                              "Zero Hunger",                                                         "Double agricultural productivity",
  "2.4",                              "Zero Hunger",                                                              "Sustainable food production",
  "2.5",                              "Zero Hunger",                                                               "Maintain genetic diversity",
  "2.a",                              "Zero Hunger",                                                                      "Increase investment",
  "2.b",                              "Zero Hunger",                                                               "Prevent trade restrictions",
  "2.c",                              "Zero Hunger",                                                    "Functioning of food commodity markets",
  "3.1",               "Good Health and Well-Being",                                                   "Reduce global maternal mortality ratio",
  "3.2",               "Good Health and Well-Being",                                           "Reduce deaths of newborns and children under 5",
  "3.3",               "Good Health and Well-Being",                                                                            "End epidemics",
  "3.4",               "Good Health and Well-Being",                               "Reduce pre-mature mortality from non communicable diseases",
  "3.5",               "Good Health and Well-Being",                                                                 "Fighting substance abuse",
  "3.6",               "Good Health and Well-Being",                                                 "Halve deaths in road traffic accididents",
  "3.7",               "Good Health and Well-Being",                                                    "Access to sexual health-care services",
  "3.8",               "Good Health and Well-Being",                                                        "Achieve universal health coverage",
  "3.9",               "Good Health and Well-Being",                                                              "Reduce death from pollution",
  "3.a",               "Good Health and Well-Being",                                                                          "Tobacco control",
  "3.b",               "Good Health and Well-Being",                                                               "Promote R&D of vaccines...",
  "3.c",               "Good Health and Well-Being",                                                                "Increase health financing",
  "3.d",               "Good Health and Well-Being",                                                     "Improve early warning risk reduction",
  "4.1",                        "Quality Education",                                                     "Free primary and secondary education",
  "4.2",                        "Quality Education",                                                    "Access to early childhood development",
  "4.3",                        "Quality Education",                                                       "Equal access to tertiary education",
  "4.4",                        "Quality Education",                                                                 "Increase relevant skills",
  "4.5",                        "Quality Education",                                                                             "Equal access",
  "4.6",                        "Quality Education",                                                                    "Literacy and numeracy",
  "4.7",                        "Quality Education",                                                "Skills to promote sustainable development",
  "4.a",                        "Quality Education",                                                           "Educational facilities for all",
  "4.b",                        "Quality Education",                                                                      "Expand scholarships",
  "4.c",                        "Quality Education",                                                    "Increase supply of qualified teachers",
  "5.1",                          "Gender Equality",                                                         "End discrimination against women",
  "5.2",                          "Gender Equality",                                                         "Eliminate violence against women",
  "5.3",                          "Gender Equality",                                                                    "End harmful practices",
  "5.4",                          "Gender Equality",                                                  "Recognize unpaid care and domestic work",
  "5.5",                          "Gender Equality",                                       "Promote women's equal opportunities for leadership",
  "5.6",                          "Gender Equality",                                                        "Universal access to sexual health",
  "5.a",                          "Gender Equality",                                            "Reforms for equal access to land ownership...",
  "5.b",                          "Gender Equality",                                                       "Technology for women's empowerment",
  "5.c",                          "Gender Equality",                                                  "Strenghten policies for gender equality",
  "6.1",               "Clean Water and Sanitation",                                                                 "Access to drinking water",
  "6.2",               "Clean Water and Sanitation",                                                         "Access to sanitation and hygiene",
  "6.3",               "Clean Water and Sanitation",                                                                    "Improve water quality",
  "6.4",               "Clean Water and Sanitation",                                                            "Increase water-use efficiency",
  "6.5",               "Clean Water and Sanitation",                                                      "Implement water resource management",
  "6.6",               "Clean Water and Sanitation",                                                         "Protect water related ecosystems",
  "6.a",               "Clean Water and Sanitation",                                                        "Expand international cooperation…",
  "6.b",               "Clean Water and Sanitation",                                                               "Support local communities…",
  "7.1",              "Affordable and Clean Energy",                                                         "Access to modern energy services",
  "7.2",              "Affordable and Clean Energy",                                                       "Increase share of renewable energy",
  "7.3",              "Affordable and Clean Energy",                                                                "Improve energy efficiency",
  "7.a",              "Affordable and Clean Energy",                                                       "Enhance international cooperation…",
  "7.b",              "Affordable and Clean Energy",                                                                   "Expand infrastructure…",
  "8.1",          "Decent Work and Economic Growth",                                                                "Sustain per capita growth",
  "8.2",          "Decent Work and Economic Growth",                                                    "Higher level of economic productivity",
  "8.3",          "Decent Work and Economic Growth",                                                    "Promote development-oriented policies",
  "8.4",          "Decent Work and Economic Growth",                                                   "Enhance resource efficiency, decouple…",
  "8.5",          "Decent Work and Economic Growth",                                                                          "Full employment",
  "8.6",          "Decent Work and Economic Growth",                                                        "Reduce youth not in employment ..",
  "8.7",          "Decent Work and Economic Growth",                                                                      "Fight forced labour",
  "8.8",          "Decent Work and Economic Growth",                                                                    "Protect labour rights",
  "8.9",          "Decent Work and Economic Growth",                                                              "Promote sustainable tourism",
  "8.10",          "Decent Work and Economic Growth",                                              "Strengthen domestic financial institutions",
  "8.a",          "Decent Work and Economic Growth",                                                           "Increase aid for trade support",
  "8.b",          "Decent Work and Economic Growth",                                                          "Strategy for youth unemployment",
  "9.1", "Industries Innovation and Infrastructure",                                                                "Develop infrastructure...",
  "9.2", "Industries Innovation and Infrastructure",                                                    "Promote sustainable industrialization",
  "9.3", "Industries Innovation and Infrastructure",                                                    "Increase access to financial services",
  "9.4", "Industries Innovation and Infrastructure",                                                "Promote environmental friendly industries",
  "9.5", "Industries Innovation and Infrastructure",                                                                   "Encouraging innovation",
  "9.a", "Industries Innovation and Infrastructure",                                                           "Enhance technological support…",
  "9.b", "Industries Innovation and Infrastructure",                                                 "Support domestic technology developement",
  "9.c", "Industries Innovation and Infrastructure",                                         "Increase access to information and communication",
  "10.1",                     "Reduced Inequalities",                                                           "Income growth of the lower 40%",
  "10.2",                     "Reduced Inequalities",                                                                                "Inclusion",
  "10.3",                     "Reduced Inequalities",                                                      "Eliminating discriminatory laws,...",
  "10.4",                     "Reduced Inequalities",                                                              "Adopt policies for equality",
  "10.5",                     "Reduced Inequalities",                                      "Regulation and monitoring of global finacial market",
  "10.6",                     "Reduced Inequalities",                                          "Enhanced representation of developing countries",
  "10.7",                     "Reduced Inequalities",                                        "Implementation of well-managed migration policies",
  "10.a",                     "Reduced Inequalities",                              "Special and differential treatment for developing countries",
  "10.b",                     "Reduced Inequalities",                                                         "Encourage development assistance",
  "10.c",                     "Reduced Inequalities",                                                                 "Reduce transaction costs",
  "11.1",       "Sustainable cities and communities",                                                                             "Safe housing",
  "11.2",       "Sustainable cities and communities",                                                          "Access to safe public transport",
  "11.3",       "Sustainable cities and communities",                                                                 "Sustainable urbanization",
  "11.4",       "Sustainable cities and communities",                                                        "Protect world's cultural heritage",
  "11.5",       "Sustainable cities and communities",                                                        "Reduce losses caused by disasters",
  "11.6",       "Sustainable cities and communities",                                                    "Reduce environmental impact of cities",
  "11.7",       "Sustainable cities and communities",                                                                   "Access to green spaces",
  "11.a",       "Sustainable cities and communities",                                   "Improve links between urban, periurban and rural areas",
  "11.b",       "Sustainable cities and communities",                                      "More cities integrating policies toward inclusion,…",
  "11.c",       "Sustainable cities and communities",                                                      "Sustainable and resilient buildings",
  "12.1",   "Responsable Consumption and Production",                         "Implement the framework of programmes on sustainable consumption",
  "12.2",   "Responsable Consumption and Production",                                                       "Efficient use of natural resources",
  "12.3",   "Responsable Consumption and Production",                                                                  "Halve global food waste",
  "12.4",   "Responsable Consumption and Production",                                                            "Sound management of chemicals",
  "12.5",   "Responsable Consumption and Production",                                                                  "Reduce waste generation",
  "12.6",   "Responsable Consumption and Production",                                                          "Encourage sustainable practices",
  "12.7",   "Responsable Consumption and Production",                                                 "Sustainable public procurement practices",
  "12.8",   "Responsable Consumption and Production",                                             "Ensure awareness for sustainable development",
  "12.a",   "Responsable Consumption and Production",                                      "Strengthen scientific and technological capacities…",
  "12.b",   "Responsable Consumption and Production",                                      "Implement tools to monitor sustainable development…",
  "12.c",   "Responsable Consumption and Production",                                            "Rationalize inefficient fossil-fuel subsidies",
  "13.1",                           "Climate Action",                                         "Strengthen resilience to climate-related hazards",
  "13.2",                           "Climate Action",                                      "Integrate clima change measure in national policies",
  "13.3",                           "Climate Action",                                    "Improve education regarding climate change mitigation",
  "13.a",                           "Climate Action",         "Implement the commitment of developed countries to support developing countries…",
  "13.b",                           "Climate Action",                          "Raising capacity for effective climate change-related planning…",
  "14.1",                         "Life below water",                                                                  "Reduce marine pollution",
  "14.2",                         "Life below water",                                                    "Protect marine and coastal ecosystems",
  "14.3",                         "Life below water",                                                             "Minimize ocean acidification",
  "14.4",                         "Life below water",                                                  "Regulate harvesting and end overfishing",
  "14.5",                         "Life below water",                                        "Conserve at least 10% of coastal and marine areas",
  "14.6",                         "Life below water",                                                       "Prohibit certain forms of fisherie",
  "14.7",                         "Life below water",                                      "Increase benefit for small island developing states",
  "14.a",                         "Life below water",                                     "Improve scientific knowledge to improve ocean health",
  "14.b",                         "Life below water",                                   "Access for smallscale fishers to resources and markets",
  "14.c",                         "Life below water",                                       "Enhance conservation and sustainable use of oceans",
  "15.1",                             "Life on Land",                                                        "Conservation of inland ecosystems",
  "15.2",                             "Life on Land",                                                            "Sustainable forest management",
  "15.3",                             "Life on Land",                                                                    "Restore degraded land",
  "15.4",                             "Life on Land",                                                      "Conservation of mountain ecosystems",
  "15.5",                             "Life on Land",                                       "Actions against degradation of natural habitats...",
  "15.6",                             "Life on Land",                        "Sharing of the benefits arising from the use of genetic resources",
  "15.7",                             "Life on Land",                                                             "End poaching and trafficking",
  "15.8",                             "Life on Land",                                                    "Reduce the impact of invasive species",
  "15.9",                             "Life on Land",                                          "Integrate ecosystem values to national planning",
  "15.a",                             "Life on Land",                                         "Increase financial resources for conservation, …",
  "15.b",                             "Life on Land",                           "Increase financial resources for sustainable forest management",
  "15.c",                             "Life on Land",                       "Improve local living conditions to reduce poaching and trafficking",
  "16.1",   "Peace, Justice and Strong Institutions",                                                          "Reduce violence and death rates",
  "16.2",   "Peace, Justice and Strong Institutions",                                               "End all forms of violence against children",
  "16.3",   "Peace, Justice and Strong Institutions",                                                                  "Equal access to justice",
  "16.4",   "Peace, Justice and Strong Institutions",                                              "Reduce illicit financial and arm flows, ...",
  "16.5",   "Peace, Justice and Strong Institutions",                                                                        "Reduce corruption",
  "16.6",   "Peace, Justice and Strong Institutions",                                                   "Effective and transparent institutions",
  "16.7",   "Peace, Justice and Strong Institutions",                                                               "Responsive decision making",
  "16.8",   "Peace, Justice and Strong Institutions",                       "Strengthen position of developing countries in global institutions",
  "16.9",   "Peace, Justice and Strong Institutions",                                                                           "Legal identity",
  "16.10",   "Peace, Justice and Strong Institutions",                                                                   "Access to information",
  "16.a",   "Peace, Justice and Strong Institutions",                                            "Strengthen relevant national institutions,...",
  "16.b",   "Peace, Justice and Strong Institutions",                                                          "Promote non discriminatory laws",
  "17.1",                "Partnership for the goals",                                                "Strengthen domestic resource mobilization",
  "17.2",                "Partnership for the goals", "Developed countries to implement fully their official development assistance commitments",
  "17.3",                "Partnership for the goals",                                                  "Mobilize additional financial resources",
  "17.4",                "Partnership for the goals",                                                                 "Attaining long term debt",
  "17.5",                "Partnership for the goals",                                                             "Investment promotion regimes",
  "17.6",                "Partnership for the goals",                                                     "Enhance international cooperation...",
  "17.7",                "Partnership for the goals",                                              "Dissemination of environmental technologies",
  "17.8",                "Partnership for the goals",                                               "Enhance the use of enabling technology,...",
  "17.9",                "Partnership for the goals",                                     "Enhance international support for SDG implementation",
  "17.10",                "Partnership for the goals",                                                              "Multilateral trading system",
  "17.11",                "Partnership for the goals",                                                 "Increase exports of developing countries",
  "17.12",                "Partnership for the goals",                                                            "Duty/quota free market access",
  "17.13",                "Partnership for the goals",                                                           "Global macroeconomic stability",
  "17.14",                "Partnership for the goals",                                     "Enhance policy coherence for sustainable development",
  "17.15",                "Partnership for the goals",                                 "Respect country's policy space for povertity eradication",
  "17.16",                "Partnership for the goals",                  "Enhance multistakeholder partnerships to support the achievement of SDG",
  "17.17",                "Partnership for the goals",                                    "Promote public private public and civil partnerhships",
  "17.18",                "Partnership for the goals",                                            "Capacity building for high data availabilitiy",
  "17.19",                "Partnership for the goals",                              "Develop measurements of progress on sustainable development"
)